# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LegendRenamer
                                 A QGIS plugin
 This plugins renames values with legend names
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-19
        copyright            : (C) 2024 by Leonid Kolesnichenko
        email                : xperience439@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Leonid Kolesnichenko'
__date__ = '2024-02-19'
__copyright__ = '(C) 2024 by Leonid Kolesnichenko'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LegendRenamer class from file LegendRenamer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .legend_renamer import LegendRenamerPlugin
    return LegendRenamerPlugin()
